### ISSUE TITLE
Allow batch withdrawal of claimable NXM

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#1173]
https://nexusmutual.slack.com/archives/C050DJKTPL3/p1719849714049159

**Comment by rackstar** [comment]
![Image](https://github.com/user-attachments/assets/538d7b41-d58c-4b45-8ca6-245f3495f1c3)

**Comment by rackstar** [comment]
# Withdraw Claimable NXM

* ensure to add validations to avoid any calls reverting
  * validate amount > 0
  * validate amount is indeed withdrawable (i.e. not locked)
  * TBD: use getClaimbleNXM for validation or call individual methods?
* ensure that withdrawClaimableNXM and getClaimableNXM should match correctly
* add option to skip claim of assessment stake (v2)
  * only v2 has optionality, v1 claim assessment stake will always be withdrawn

**Comment by rackstar** [comment]
## Withdraw Governance Rewards
1. validate and skip is 0 rewards
```javascript
  GV.getPendingReward(account) => (uint pendingDAppReward)
```
2. withdraw gov rewards
```javascript
  // fromGovernance = true
  // fromAssessment = false
  // batchSize = 100
  TC.withdrawPendingRewards([account, fromGovernance, fromAssessment, batchSize])
```

**Comment by rackstar** [comment]
## Withdraw Claim Assessment Rewards
1. validation (see FE code screenshot below)
```javascript
  AS.getRewards(account) => (uint totalPendingAmountInNXM, uint withdrawableAmountInNXM, uint withdrawableUntilIndex)
  AS.stakeOf(account) => (uint96 amount, uint104 rewardsWithdrawableFromIndex, uint16 fraudCount)
  AS.getVoteCountOfAssessor(account) => (uint voteCount)
```
2. withdraw claim assessment rewards
```javascript
  // fromGovernance = false
  // fromAssessment = true
  // batchSize = 0 // bug in assessment contract

  TC.withdrawPendingRewards([account, fromGovernance, fromAssessment, batchSize])
```


FE Code block:
![Image](https://github.com/user-attachments/assets/019124c4-2356-402e-acc8-9f318282d4ac)

**Comment by rackstar** [comment]
## Withdraw Claim Assessment Stake (optional)
1. Read param if claim assessment stake should be withdrawn or not 
2. validate if 0 stake / isStakeLocked
```javascript
  AS.stakeOf(account) => (uint96 amount, uint104 rewardsWithdrawableFromIndex, uint16 fraudCount)
  AS.isStakeLocked(account) => bool
```
3. withdraw claim assessment stake
```javascript
  AS.unstake(amount, account)
```

**Comment by rackstar** [comment]
## Withdraw Staking Pools Deposits / Rewards

1. calculate trancheIds (see FE screenshot)
2. internal function that takes in `tokenIds`
```javascript
// withdrawStake = true
// withdrawRewards = true

// for loop 
  uint poolId = stakingNFT.stakingPoolOf(tokenIds[i]);
  stakingPool(poolId).withdraw(tokenId, withdrawStake, withdrawRewards, trancheIds)
```

FE code block:


![Image](https://github.com/user-attachments/assets/8bfb3b31-7933-4f82-92c3-2d6251651062)

**Comment by rackstar** [comment]
## Withdraw Staking Pools Manager Rewards
1. Validate if managed pools array is empty or manager rewards is 0
2. calculate trancheId (see https://github.com/NexusMutual/smart-contracts/issues/1173#issuecomment-2236390945)
```javascript
stakingViewer.getManagerPoolsAndRewards(manager)
// or call nexusViewer.getClaimableNXM(manager, tokenIds) once at the top for all withdrawal validation
```
3. Withdraw staking pool manager rewards
```javascript
// withdrawStake = false
// withdrawRewards = true

// for loop
  stakingPool(pools[i].poolId).withdraw(0, withdrawStake, withdrawRewards, trancheIds)
```

**Comment by rackstar** [comment]
## Tasks

* modify withdraw functions to remove revert and support member address parameter
  * [x] TC.withdrawPendingRewards
  * [ ] AS.unstakeFor
  * [ ] stakingPool(poolId).withdraw
  * [ ] TC.withdrawCoverNote
  * [ ] TC.withdrawClaimAssessmentTokens
  * [ ] legacyPooledStaking.withdrawForUser
  * [ ] legacyPooledStaking.withdrawReward
