### ISSUE TITLE
npm run deploy-local seems not working

### ISSUE THREAD

**Issue by dahof1** [NexusMutual/smart-contracts#1217]
I wanted to play around with the nexus mutual codebase, but it seems the `deploy.js` script is outdated. 

Here a some things i recognized so far:
- The script requires a file `const products = require('../v2-migration/output/migratableProducts.json')` which is not in the repo
- `DisposableGateway` is deprecated and not in the latest version anymore
- `ProductsV1` is not in the latest version anymore
- `CoverMigrator` uses `ProductsV1` and is therefore not working
- Deployment of `SwapOperator` is passing outdated constructor arguments (in script 7, contract needs 10)

I tried the latest commit from `release-candidate` branch and run `npm run deploy-local` (after npm i, and npm test).

It would be awesome if you can have a look or maybe point me to the right direction. Thanks!

**Comment by MilGard91** [comment]
Thank you for reporting this @dahof1, we will look into it. In the meantime you can use tenderly forks to to play around with the current setup we have.

**Comment by dahof1** [comment]
Hi @MilGard91 thanks for the tip. Sorry for asking again. but do you have more details how to use the tenderly fork?

**Comment by MilGard91** [comment]
@dahof1 sorry for late reply. On [tenderly](https://tenderly.co/) when you create an account, you will have a tab Virtual TestNets, there you can create a new virtual test net from mainnet. It will have the state of the chain on the latest block 
 then you can use it's RPC URL for the provider and play around with the contracts and methods on them.

For more info you can check their [documentation](https://docs.tenderly.co/virtual-testnets).
