### ISSUE TITLE
Audit - Staking H1: Wrong bitwise operations make several functions unusable

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#297]
The getters and setters getItemAt(), setItemAt() and newCoverAmount() in StakingTypesLib.sol are intended to be used for extracting or storing a variable inside custom types that can hold multiple variables at once. For example, a custom type of uint256 can hold up to 8x uint32 variables. To implement this functionality, bitwise operations are used to move and place the variables in the right position.

However, the provided implementation doesn’t achieve the desired functionality as it lacks proper type casts and has a number of reversed bitwise shift operations. 

A detailed overview of the issues along with our suggestions for fixes is listed below:

_StakingTypesLib.sol_
```
function newCoverAmount(
  uint48 coverAmount,
  uint16 bucketId
) internal pure returns (CoverAmount) {


  // Dedaub: uint64() casting before shifting `coverAmount`
  // return CoverAmount.wrap( (        coverAmount  << 16 ) | bucketId );  // Old
  return    CoverAmount.wrap( ( uint64(coverAmount) << 16 ) | bucketId );
                                ^^^^^^^           ^
}
----------------------------------------------------------------------------------
function getItemAt(
  CoverAmountGroup items,
  uint index
) internal pure returns (CoverAmount) {
  ...
// Dedaub: Bitwise SHIFT RIGHT instead of SHIFT LEFT
  // uint64 item = uint64( underlying << (index * 64) );  // Old
  uint64    item = uint64( underlying >> (index * 64) );
                                      ^^
  ...
}
----------------------------------------------------------------------------------
function setItemAt(
  CoverAmountGroup items,
  uint index,
  CoverAmount item
) internal pure returns (CoverAmountGroup) {


  // Dedaub: uint() casting before shifting `type(uint64).max` &&  
     No need for uint64() cast for `index * 64`
  // uint mask = ~(       type(uint64).max   << uint64(index * 64) );  // Old
  uint mask    = ~( uint( type(uint64).max ) <<       (index * 64) );
                    ^^^^^                  ^    ^^^^^^


  // Dedaub: Change uint() scope to contain `item` before shifting  &&  
     No need for uint64() cast for `index * 64`
  // uint itemUnderlying = 
        uint( CoverAmount.unwrap(item)   << uint64(index * 64) );  // Old
  uint itemUnderlying    = 
        uint( CoverAmount.unwrap(item) ) <<       (index * 64)  ;  
                                       ^    ^^^^^^             ^
  ...
}
----------------------------------------------------------------------------------
function getItemAt(
  BucketTrancheGroup items,
  uint index
) internal pure returns (uint32) {
   ...
  // Dedaub: Bitwise SHIFT RIGHT instead of SHIFT LEFT
  // return uint32( underlying << (index * 32) );  // Old
  return    uint32( underlying >> (index * 32) );
                               ^^
}
----------------------------------------------------------------------------------
function setItemAt(
  BucketTrancheGroup items,
  uint index,
  uint32 value
) internal pure returns (BucketTrancheGroup) {


  // Dedaub: uint() casting before shifting `type(uint32).max`  &&  
     No need for uint32() cast for `index * 32`
  // uint mask = ~(       type(uint32).max   << uint32(index * 32) );  // Old
  uint mask    = ~( uint( type(uint32).max ) <<       (index * 32) );
                    ^^^^^                  ^    ^^^^^^

  // Dedaub: There is a missing shifting operation for positioning ‘value’ 
     at the right place before performing bitwise OR
  uint itemUnderlying = uint( value ) << (index * 32);
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  // Dedaub: Change `value` with `itemUnderlying
  // uint groupUnderlying = 
        BucketTrancheGroup.unwrap(items) & mask | value;  // Old
  uint groupUnderlying    = 
        BucketTrancheGroup.unwrap(items) & mask | itemUnderlying;
                                                  ^^^^^^^^^^^^^^
  ...
}

```

—-------------------------------------------------------------------
Furthermore, there are two more issues involving bitwise operations that need attention in StakingPool.sol.

Here amountPerTranche should hold the cover allocation for a specific tranche indexed by i and extracted from packedCoverTrancheAllocation, but instead corrupt data will be retrieved having the index multiplied by 8 and casting the variable with uint32().

_StakingPool::deallocateStakeForCover():723_
```
// Dedaub: Shift right needs to be `(i * 32)` instead of `(i * 8)`
uint amountPerTranche = uint32(packedCoverTrancheAllocation >> (i * 8));
                                                                    ^
```

In the following part, uint() casting is required in order to properly shift trancheAllocation without destroying the data it holds.

_StakingPool::updateExpiringCoverAmounts():961_
```
// Dedaub: uint() casting around `trancheAllocation` is required  &&  
   No need for uint32() cast for `i * 32`
// packedCoverTrancheAllocation |=      
           trancheAllocation  << uint32(i * 32);  // Old
packedCoverTrancheAllocation    |= 
      uint(trancheAllocation) <<       (i * 32);
      ^^^^^                 ^    ^^^^^^
```

Note that all above suggestions have not been tested and should be verified by the developers.

**Comment by kyledewy** [comment]
All  issues seem to be resolved on the following lines of nexus-v2 branch:
- [x] [uint64() casting before shifting `coverAmount`](https://github.com/NexusMutual/smart-contracts/blob/nexus-v2/contracts/modules/staking/StakingTypesLib.sol#L27)
- [x] [Bitwise SHIFT RIGHT instead of SHIFT LEFT](https://github.com/NexusMutual/smart-contracts/blob/nexus-v2/contracts/modules/staking/StakingTypesLib.sol#L37)

- [x] [uint() casting before shifting `type(uint64).max` &&  
     No need for uint64() cast for `index * 64`](https://github.com/NexusMutual/smart-contracts/blob/nexus-v2/contracts/modules/staking/StakingTypesLib.sol#L48)
     
- [x] [Change uint() scope to contain `item` before shifting  &&  
     No need for uint64() cast for `index * 64`](https://github.com/NexusMutual/smart-contracts/blob/nexus-v2/contracts/modules/staking/StakingTypesLib.sol#L49)

- [x] [Bitwise SHIFT RIGHT instead of SHIFT LEFT](https://github.com/NexusMutual/smart-contracts/blob/nexus-v2/contracts/modules/staking/StakingTypesLib.sol#L61)

- [x] [uint() casting before shifting `type(uint32).max`  &&  
     No need for uint32() cast for `index * 32`](https://github.com/NexusMutual/smart-contracts/blob/nexus-v2/contracts/modules/staking/StakingTypesLib.sol#L71)

- [x] [There is a missing shifting operation for positioning ‘value’ 
     at the right place before performing bitwise OR](https://github.com/NexusMutual/smart-contracts/blob/nexus-v2/contracts/modules/staking/StakingTypesLib.sol#L72)
- [x] [Change `value` with `itemUnderlying](https://github.com/NexusMutual/smart-contracts/blob/nexus-v2/contracts/modules/staking/StakingTypesLib.sol#L73)
- [x] [Shift right needs to be `(i * 32)` instead of `(i * 8)`](https://github.com/NexusMutual/smart-contracts/blob/nexus-v2/contracts/modules/staking/StakingTypesLib.sol#L61)
- [x] [uint() casting around `trancheAllocation` is required  &&  
   No need for uint32() cast for `i * 32`](https://github.com/NexusMutual/smart-contracts/blob/nexus-v2/contracts/modules/staking/StakingPool.sol#L981)
