### ISSUE TITLE
Audit - Staking M1: depositTo() will always revert when invoked by a new depositor

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#298]
A new depositor can call depositTo() and provide a DepositRequest with tokenId == 0. This should cause the contract to mint a new NFT and send it to the provided destination. 

When request.tokenId == 0,  the if(isNewToken) code block below will run, and this will call _mint(to,request.tokenId). However the NFT with tokenId == 0 is already created in the initialize() function, and sent to the manager. Therefore, _mint() will fail and depositTo() will revert every time a new depositor calls it.

_StakingPool::depositTo():372_
```
bool isNewToken = request.tokenId == 0;

if (isNewToken) {
    tokenIds[i] = totalSupply++;
    address to = request.destination == address(0) 
                 ? msg.sender 
                 : request.destination;
    _mint(to, request.tokenId);
} else {
  tokenIds[i] = request.tokenId;
}
```

The above issue can be resolved by calling _mint(to,tokenIds[i]) instead.

**Comment by kyledewy** [comment]
`_mint()` now uses `tokenIds[i]` as suggested https://github.com/NexusMutual/smart-contracts/blob/nexus-v2/contracts/modules/staking/StakingPool.sol#L374
