### ISSUE TITLE
Audit - Staking M3: getTotalCapacities() will always revert

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#300]
This function calculates and returns the total capacity that a number of tranches can provide per product.

In the function there is a loop that iterates over the range of the tranches that a cover will be applied to. Since <= is used instead of < in the loop, this will exceed the valid trancheCount by 1 and will lead the function to revert.

_StakingPool::getTotalCapacities():878_
```
// Dedaub: Loop uses <= instead of <
for (uint i = 0; i <= trancheCount; i++) {
  ...
}
```

**Comment by kyledewy** [comment]
Now uses `<` instead of `<=` https://github.com/NexusMutual/smart-contracts/blob/nexus-v2/contracts/modules/staking/StakingPool.sol#L898
