### ISSUE TITLE
Audit - Staking M4: Deposit extensions when initial tranche has expired are impossible due to unallocated array

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#301]
The function extendDeposit() tries to create a new DepositRequest when the initial tranche has expired, in order to create a new deposit which is equal to the withdrawn amounts plus the topUpAmount.

However, the depositRequests array never gets allocated before the new DespositRequest is assigned, which will lead the function to revert under these circumstances.

_StakingPool::getTotalCapacities():1041_
```
// Dedaub: `depositRequests` doesn't get allocated
DepositRequest[] memory depositRequests;
depositRequests[0] = (
  DepositRequest(
     withdrawnStake + topUpAmount, // amount
     newTrancheId,                 // trancheId
     tokenId,                      // tokenId
     msg.sender                    // destination
  )
);
```

**Comment by kyledewy** [comment]
- [x] `depositRequest` array now allocates space for the new deposit https://github.com/NexusMutual/smart-contracts/blob/nexus-v2/contracts/modules/staking/StakingPool.sol#L1046
