### ISSUE TITLE
Audit - Staking M5: Incorrect use of constructor in a proxy implementation

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#302]
A limitation of proxied contracts is that they cannot use constructors, since the constructor would modify the implementation storage instead of the proxy storage.

Immutable variables are not affected by this limitation, since they are not stored in storage but compiled in the code.  As a consequence, the initialization of nxm, coverContract and tokenController in  StakingPool::constructor is valid, since these variables are immutable.

However, StakingPool::constructor also calls the parent SolmateERC721 constructor:

```
constructor (
  string memory _name,
  string memory _symbol,
  address _token,
  address _coverContract,
  ITokenController _tokenController
) SolmateERC721(_name, _symbol) {
  nxm = INXMToken(_token);
  coverContract = _coverContract;
  tokenController = _tokenController;
}
```

But SolmateERC721 does not use immutable variables, so effectively name and symbol will not be properly stored.

We recommend against using a constructor and initialize all variables in StakingPool::initialize, to ensure that no issues with the proxy pattern arise.

**Comment by shark0der** [comment]
The assignment is already happening inside the `initialize` function: https://github.com/NexusMutual/smart-contracts/blob/nexus-v2/contracts/modules/staking/StakingPool.sol#L175-L176

Whenever we bring the new `ERC721N` implementation we'll have to fix any inconsistencies, which is outside of the scope of this issue.

**Comment by danoctavian** [comment]
Good point, i ommited those 2 lines.

looks good ✅ 

```name = string(abi.encodePacked("Nexus Mutual Staking Pool #", Strings.toString(_poolId)));
    symbol = string(abi.encodePacked("NMSP-", Strings.toString(_poolId)));```
