### ISSUE TITLE
Audit - Staking 3.1.2 Drain of StakingPool.sol due to uninitialised stakeToWithdraw and rewardsToWithdraw in StakingPool::withdraw()

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#307]
[StakingPool.sol#L508](https://github.com/NexusMutual/smart-contracts/blob/14a7ed6f5b6df877a2cb7eb9fd390c9cb216ccb2/contracts/modules/staking/StakingPool.sol#L508)

**Description**
For each WithdrawRequest a staker supplies to StakingPool::withdraw() the values of stakeToWithdraw and rewardsToWithdraw are calculated ([StakingPool.sol#L544](https://github.com/NexusMutual/smart-contracts/blob/14a7ed6f5b6df877a2cb7eb9fd390c9cb216ccb2/contracts/modules/staking/StakingPool.sol#L544) and [StakingPool.sol#L559](https://github.com/NexusMutual/smart-contracts/blob/14a7ed6f5b6df877a2cb7eb9fd390c9cb216ccb2/contracts/modules/staking/StakingPool.sol#L559)) and then later transferred to the staker at [StakingPool.sol#L570](https://github.com/NexusMutual/smart-contracts/blob/14a7ed6f5b6df877a2cb7eb9fd390c9cb216ccb2/contracts/modules/staking/StakingPool.sol#L570). However, the values for stakeToWithdraw and rewardsToWithdraw are not initialised to zero for each WithdrawRequest.

As a result, a staker could supply an initial WithdrawRequest, containing the details of an expired tranche they deposited into, followed by additional WithdrawRequests with empty trancheIds arrays. This would result in stakeToWithdraw and rewardsToWithdraw being set to the result of the first WithdrawRequest, the for-loop at [StakingPool.sol#L525](https://github.com/NexusMutual/smart-contracts/blob/14a7ed6f5b6df877a2cb7eb9fd390c9cb216ccb2/contracts/modules/staking/StakingPool.sol#L525) being skipped, and the token transferral happening again with the same stakeToWithdraw and rewardsToWithdraw values calculated in the first iteration. Numerous WithdrawRequests can be added, and this would be sufficient to drain the pool of its staked NXM.

**Remediation**
The outermost loop should set stakeToWithdraw and rewardsToWithdraw to zero upon execution, to ensure that only the stake and rewards that are owed to the token owner can be withdrawn.

**Comment by danoctavian** [comment]
Fixed  ✅
 
The  stakeToWithdraw and rewardsToWithdraw are now scoped inside the outermost loop. 

This effectively means they are set to 0 on every outermost loop execution.

https://github.com/NexusMutual/smart-contracts/blob/13f9ab594f5c0e1fe4d0b67cf48004c79763d6b2/contracts/modules/staking/StakingPool.sol#L513

The return function values are now different and they are accumulators of these 2 values over each loop as shown below:

https://github.com/NexusMutual/smart-contracts/blob/13f9ab594f5c0e1fe4d0b67cf48004c79763d6b2/contracts/modules/staking/StakingPool.sol#L568
