### ISSUE TITLE
Audit - Staking 3.1.4 Pool Managers can arbitrarily increase their pending rewards

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#309]
[StakingPool.sol#L1234](https://github.com/NexusMutual/smart-contracts/blob/14a7ed6f5b6df877a2cb7eb9fd390c9cb216ccb2/contracts/modules/staking/StakingPool.sol#L1234)

**Description**
When a manager updates a staking pool's fee, their pending rewards are updated to reflect their earnings before the fee update. This is done for each of the currently active tranches. However, as lastAccNxmPerRewardShare is not updated for each deposit, a pool manager can repeatedly call setPoolFee() to increase their pending rewards. This can be done reliably by a malicious pool manager by calling setPoolFee() with the current pool fee.

**Remediation**
After the pending rewards are updated for the reward shares of each tranche, lastAccNxmPerRewardShare should be updated to _accNxmPerRewardsShare.

**Comment by danoctavian** [comment]
https://github.com/NexusMutual/smart-contracts/blob/13f9ab594f5c0e1fe4d0b67cf48004c79763d6b2/contracts/modules/staking/StakingPool.sol#L1263

The update is performed as recommended for each tranche:

feeDeposit.lastAccNxmPerRewardShare = _accNxmPerRewardsShare;
