### ISSUE TITLE
Audit - Pool 3.3.4 Missing price oracle staleness check

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#316]
[PriceFeedOracle.sol#L94](https://github.com/NexusMutual/smart-contracts/blob/14a7ed6f5b6df877a2cb7eb9fd390c9cb216ccb2/contracts/modules/capital/PriceFeedOracle.sol#L94)

**Description**
The _getAssetToEthRate function did not check for stale rates. This could lead to inconsistencies in the pricing of assets in the system. Since all major actions of the system require valid asset prices to calculate all asset values in terms of ETH, an invalid or stale asset value could lead to incorrect system metrics.

**Remediation**
It is recommended to enforce a staleness check in _getAssetToEthRate to properly ensure that rates are current at the time of operation.

**Comment by roxdanila** [comment]
Add Tenderly alerts for oracle staleness.

**Comment by MilGard91** [comment]
Update rate:
- [DAI/ETH](https://data.chain.link/ethereum/mainnet/stablecoins/dai-eth) every 24h or if the deviation is over 1%
- [stETH/ETH](https://data.chain.link/ethereum/mainnet/crypto-eth/steth-eth) every 24h or if the deviation is over 2%
- Enzyme - to be found

**Comment by roxdanila** [comment]
https://github.com/NexusMutual/tenderly-workers/pull/1
