### ISSUE TITLE
Audit - Staking 3.3.2 Potentially incorrect calculation of tranche ID range

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#318]
[StakingPool.sol#L353](https://github.com/NexusMutual/smart-contracts/blob/14a7ed6f5b6df877a2cb7eb9fd390c9cb216ccb2/contracts/modules/staking/StakingPool.sol#L353) [StakingPool.sol#L994](https://github.com/NexusMutual/smart-contracts/blob/14a7ed6f5b6df877a2cb7eb9fd390c9cb216ccb2/contracts/modules/staking/StakingPool.sol#L994) [StakingPool.sol#L1244](https://github.com/NexusMutual/smart-contracts/blob/14a7ed6f5b6df877a2cb7eb9fd390c9cb216ccb2/contracts/modules/staking/StakingPool.sol#L1244)

**Description**
The maximum tranche ID (maxTranche) calculated in the depositTo() and extendDeposit() functions both equate to the 9th tranche, starting from the first active tranche. This allows stakers to stake into tranches that have not yet become active, as it was understood that only 8 tranches, starting from the first active tranche, are active at any given moment.

The calculation of toTrancheId in setPoolFee() seems to be handled similarly.

**Remediation**
If this behaviour is undesired, the calculation of maxTranche should be calculated using _firstActiveTrancheId + MAX_ACTIVE_TRANCHES - 1, to ensure that the 9th tranche is appropriately excluded. toTrancheId should also be decremented by 1.

**Comment by danoctavian** [comment]
Fixed

As recommended the depositTo() function is updated 

https://github.com/NexusMutual/smart-contracts/blob/13f9ab594f5c0e1fe4d0b67cf48004c79763d6b2/contracts/modules/staking/StakingPool.sol#L354

And the extendDeposit() function is updated:

https://github.com/NexusMutual/smart-contracts/blob/13f9ab594f5c0e1fe4d0b67cf48004c79763d6b2/contracts/modules/staking/StakingPool.sol#L1024
