### ISSUE TITLE
Clarify the usage of ipfs hash in the ProductType struct

### ISSUE THREAD

**Issue by mixplore** [NexusMutual/smart-contracts#368]
We want to keep the cover wording (terms and conditions) on-chain in IPFS. For that we need to link the IPFS hash to our product types.

Currently the `ProductType` struct holds only 2 props:
```
uint8 claimMethod;
uint16 gracePeriodInDays;
```
We need another prop to hold the IPFS hash of the corresponding cover wording (terms and conditions).

**TBD** products link to product type, currently done using a `uint16 productType;`

**Comment by roxdanila** [comment]
@mixplore just clarified this one. The IPFS hash is emitted as an event when a new product type is added / edited (`ProductSet` and `ProductTypeSet` events)
