### ISSUE TITLE
Implement tokenURI() for Cover and StakingNFTs

### ISSUE THREAD

**Issue by kyledewy** [NexusMutual/smart-contracts#372]
Options;
1.) We can implement a link to an ipfs address
2.) Let the tokenURI() function build and encode the data we intend to store

**Comment by shark0der** [comment]
Boy I have news for you!

[staking.svg](https://user-images.githubusercontent.com/528959/222679692-018d3adf-f8d0-4dad-88a2-277665fbe2b3.svg)
[cover.svg](https://user-images.githubusercontent.com/528959/222679691-a3e4958c-84a9-4e43-9bc6-8519d7732a28.svg)
