### ISSUE TITLE
Code review: Cover.sol

### ISSUE THREAD

**Issue by kyledewy** [NexusMutual/smart-contracts#377]

**Comment by kyledewy** [comment]
I think it may be worth testing if etherscan is going to be able to parse the MinimalBeaconProxy. This [eip](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1967.md)  on storage slots asks the beacon to have an implementation() getter. It also mentions where the address should be stored, but hopefully block explorers are ok with the view function.

**Comment by kyledewy** [comment]
To reduce the number of times Cover calls out to the pool contract, maybe we can pass an array of tokens to `pool.getTokenPrice()`
![Image](https://user-images.githubusercontent.com/15720036/190379923-36163dbe-8f6e-4d7f-8ba9-138881354b54.png)

**Comment by kyledewy** [comment]
Prefix these functions with an underscore to show they are internal?


![Image](https://user-images.githubusercontent.com/15720036/190381860-88ca939d-24b5-45e3-83ab-899110fc9d34.png)

**Comment by roxdanila** [comment]
@danoctavian pls take a look over the above comments and reply.

**Comment by danoctavian** [comment]
> Prefix these functions with an underscore to show they are internal? I don't memberRoles() or mcr() are being used anywhere.
> 
> ![Image](https://user-images.githubusercontent.com/15720036/190381860-88ca939d-24b5-45e3-83ab-899110fc9d34.png)

We haven't been using the _ underscore prefix convention so far for internal functions, i'd suggest we don't start out with it now unless there's a good reason.

**Comment by kyledewy** [comment]
I think in practice you would see a number a bit higher, depending on memory usage, but I agree it's probably overkill here. Especially with the conditional there.
