### ISSUE TITLE
Investigate if etherscan can parse MinimalBeaconProxy.sol

### ISSUE THREAD

**Issue by danoctavian** [NexusMutual/smart-contracts#389]
Test if etherscan is going to be able to parse the MinimalBeaconProxy. This [eip](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1967.md) on storage slots asks the beacon to have an implementation() getter.

It also mentions where the address should be stored, but hopefully block explorers are ok with the view function.

Can use a testnet for this; assuming etherscan functionality is the same.

If Etherscan is able to identify it, change the name of the getter function _implementation() to implementation() and make it public.

**Comment by roxdanila** [comment]
From Kyle: 

I checked the MinimalBeaconProxy on Etherscan and it seems that it isn't automatically recognized as a proxy, but Etherscan has an option to verify it as a custom proxy. Note that this seems to first require a transaction to go through it. (specifically a delegate call to the implementation). Once this happens it allows you to verify it and read/write it as a custom proxy.
I did it manually, although it seems it can also be done via the API
