### ISSUE TITLE
Cover Product: Merge product management function into 2 functions: `setProducts()` and `setProductTypes()`

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#412]

**Comment by kyledewy** [comment]
- rename staking `setProducts` to `setStakedProducts`
- merge cover.edit/add/remove/deprecate products into a single function `cover.setSupportedProducts()`
- take inputs to cover.setProducts() in a struct ProductParams (maybe change name a little to avoid conflict with staking.ProductParams)
-  add an explicit deprecated flag to the Product struct

**Comment by roxdanila** [comment]
@kyledewy maybe rename `staking.ProductParams` to `staking.StakedProductParams` for consistency with `setStakedProducts()`
