### ISSUE TITLE
Get new v2 cover id after v1 cover migration

### ISSUE THREAD

**Issue by mixplore** [NexusMutual/smart-contracts#437]
### Context
When submitting a claim for an old v1 cover, we first need to migrate the cover to a v2 one and then call the submit claim method. 
After the cover migration, the new cover has a new `coverId`. 
We need that id returned from the migration method so we can use it further as param for submit claim method.

**Comment by danoctavian** [comment]
We need an event here. for cover migration runs.

It is indeed missing now.

**Comment by danoctavian** [comment]
we'll add a CoverMigrated event for simplicity.
