### ISSUE TITLE
Check `claimPayoutAddress` mapping storage

### ISSUE THREAD

**Issue by shark0der** [NexusMutual/smart-contracts#438]
Make sure `claimPayoutAddress` was only used by Armor so we don't end up with some other used slot that we're unaware of. We have the option to perform a MR upgrade and disable it pre-upgrade or upgrade and check after the upgrade that no-one has used it in the meantime.

**Comment by shark0der** [comment]
For the second option: we'd better extend the function to accept mapping keys as input (array of addresses) and be able to clean up any additional storage slot from that mapping.

**Comment by roxdanila** [comment]
Fork test
