### ISSUE TITLE
Review existing migration guide and finalize the spec if it requires changes

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#572]
- [ ] review existing spec & implementation
    - [ ] cover migration (cover notes)
    - [ ] rewards migration (claim rewards, governance rewards, staking rewards)
    - [ ] stake migration (deposits / allocations)
    - [ ] claim assessment stake 
    - [ ] any changes required?
- [ ] list of values that need to be hardcoded / snapshoted
- [ ] list of scripts needed

**Comment by danoctavian** [comment]
Analysis provided at the base of the migration document.

https://docs.google.com/document/d/1yP0CpM20lL3POd3EbQ8GodzntFNg0mACNnvKa10WTAE/edit#heading=h.4skkhhjor7ud


**Handling rewards and deposits**

We made the decision to keep the code generation scripts. For Assessment rewards, sending them out to the users allows us to phase out all the old code.  The remainder of NXM tokens in ClaimsReward are sent into TokenController.

For Assessment and Governance  rewards withdrawal the `withdrawPendingRewards` is to be used.

To withdraw tokens locked for assessment `withdrawClaimAssessmentTokens` is to be run.

**Handling the PooledStaking migration and rewards**

We need to validate the staking pool migration works correctly.

The top staker list is to be reworked.

We are to remove the 90 day limit for migration.

```    require(block.timestamp <= migrationDeadline, "Migration period has ended");
```
}

We are to check that withdrawing the deposit does not interfere with migrating a staking pool.

Open question: what is the price used when migrating products to the pool configuration?

**Comment by roxdanila** [comment]
Open question: what is the price used when migrating products to the pool configuration?

Discussed here: https://nexusmutual.slack.com/archives/G010M0U3BT8/p1672741372273939
