### ISSUE TITLE
StakingPool.requestAllocation() unit tests

### ISSUE THREAD

**Issue by kyledewy** [NexusMutual/smart-contracts#582]
Unit tests have been started, mostly focusing on premium + pricing in this PR: https://github.com/NexusMutual/smart-contracts/pull/543

`requestAllocation()` is complex and should include tests verifying other aspects of it's functionality like `updateStoredAllocations` and `rewards` & `rewardsPerSecond`. 
Some of the pricing tests can be removed as well, as they are redundantly tested in `StakingPool.calculatePremium.js`

**Comment by roxdanila** [comment]
Duplicate of #492
