### ISSUE TITLE
Fork test: Migrate PooledStaking

### ISSUE THREAD

**Issue by danoctavian** [NexusMutual/smart-contracts#608]
Complete the following stages in the fork test migration-v2.js file.

- process all PooledStaking pending actions
- migrate top stakers to new v2 staking pools

**Comment by roxdanila** [comment]
@danoctavian re `migrate top stakers to new v2 staking pools`:

We'll have a hardcoded list of members that will migrate their stake to create a new staking pool and move over their existing product allocations and current prices as initial state.

List of stakers to be mkigrated to staking pool managers:

- [ ] 0x1337def1fc06783d4b03cb8c1bf3ebf7d0593fc4
- [ ] 0x963df0066ff8345922df88eebeb1095be4e4e12e
- [ ] 0x87b2a7559d85f4653f13e6546a14189cd5455d45
- [ ] 0x46de0c6f149be3885f28e54bb4d302cb2c505bc2

Everybody else should have their stakes unlocked and will have the option to withdraw it anytime, and if they decide, they can then delegate to any existing staking pool manually.

This will involve some changes to the PoolStaking.sol current logic FYI.

**Comment by roxdanila** [comment]
Last TODO: push all rewards before processing and disable functionality to accumulate more
