### ISSUE TITLE
Fork test: Update basic-functionality tests to the new v2 setup.

### ISSUE THREAD

**Issue by danoctavian** [NexusMutual/smart-contracts#614]
Adapt existing basic-functionality-tests.js that run after every upgrade to V2.

Some tests may not make sense anymore.

What must be covered:

* subsequent contract upgrades
** pool
** Master
** Governance
** a proxy contract
** a non-proxy contract

* buy protocol cover
* buy yield token cover
* edit cover (optional)
* createStakingPool
* stake
* emergency pause/unpause

**Comment by shark0der** [comment]
Add a check for contract deps: https://github.com/NexusMutual/smart-contracts/pull/640#discussion_r1090714609
