### ISSUE TITLE
Update readme to link to audits on docs.nexusmutual.io

### ISSUE THREAD

**Issue by shark0der** [NexusMutual/smart-contracts#657]
Let's have a single place for the audits, the documentation: https://docs.nexusmutual.io/overview/resources/audits-and-security

Todo:
- [ ] Update audits link on the main 
- [ ] Update audits section of the contracts repo

**Comment by adityakode** [comment]
Hi, I would like to work on the issue. 
Can you please explain what do I have to do ?
