### ISSUE TITLE
Suspected bugs in cover contract

### ISSUE THREAD

**Issue by shark0der** [NexusMutual/smart-contracts#713]
suspicion 1: buy cover, edit the cover to reduce the amount and create a new segment, claim for the initial segment, the burnStake function calculates the active cover expiration bucket id using the claimed segment start+end+gracePeriod but that value is probably no longer valid since the cover was edited.

suspicion 2: buy cover, edit the cover to reduce the amount (could also be happening when increasing), claim for the initial segment, the burnStake function loops through the allocations and calculates the new coverAmountInNXM but it uses segment.amount for division, which could have any value now since the cover was edited hence the new allocations are probably wrong.

**Comment by kyledewy** [comment]
It seems these suspicions are valid. I'm not 100% sure what the correct behaviour should be. I added that sequence of calls to test and made a few changes, but it needs more. wip here: https://github.com/NexusMutual/smart-contracts/pull/724
