### ISSUE TITLE
TotalBalanceOf unit & integration tests

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#756]
Write unit & integration tests for the totalBalanceOf (with and without delegations) from this PR: https://github.com/NexusMutual/smart-contracts/pull/753/

Open a separate PR based on this branch ^

**Comment by kyledewy** [comment]
added some unit tests skeletons and implemented the ones for `totalBalanceOf()` 
https://github.com/NexusMutual/smart-contracts/pull/757/files
