### ISSUE TITLE
StakingProducts.recalculateEffectiveWeights should check for product existence in StakingPool

### ISSUE THREAD

**Issue by kyledewy** [NexusMutual/smart-contracts#801]

**Comment by kyledewy** [comment]
Sorry about that. This didn't end up being an issue. I wrote a test for this situation in `recalculateEffectiveWeights` unit test on this [branch](https://github.com/NexusMutual/smart-contracts/pull/811/files#diff-34cca064c6f11516e00a2ab79b0c01f1a4f4b66dfbca81bdee7b36292342857e)  instead to show that its a no-op.

**Comment by roxdanila** [comment]
Closing as no-op
