### ISSUE TITLE
Fix calculate effective weight rounding to 0 after a burn leaves less than 1 capacity unit

### ISSUE THREAD

**Issue by 0xdewy** [NexusMutual/smart-contracts#842]
If a burn leaves 0 capacity units ( < 1e16) the effective weight calculations are currently treating it as a pool with 0 allocations and 0 capacity. This returns the targetWeight, when the real effective weight could be quite high due to the burns.

Risk seems low, since it would require a claim to leave less than .01 nxm. This would allow the manager to possibly give a bit extra capacity into the pool, despite possibly being over allocated.

**Comment by kyledewy** [comment]
For fixing this we could either halt the pool when anything less than 1 capacity unit is remaining, or else change `getEffectiveWeight` to consider that 0 capacity doesn't always mean that it's a non-active pool.

**Comment by roxdanila** [comment]
cc @shark0der for direction

**Comment by kyledewy** [comment]
Ok nice, that's what I was thinking as well. Share inflation also goes up rapidly as you approach 0. In fact, the inflation thing may not even be much of an issue if we halt at 1 capacity unit.
