### ISSUE TITLE
View-only contracts to read member tokens (i.e. stakes, rewards) in various parts of the protocol

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#853]
> - make sure inputs such as batch size or max records are consistently used across all rewards-related functions
> - don't revert if there are no rewards to be withdrawn
>  also related to #768 

The consumer of this will be the UI. 
- what are the needs of the UI?
- what's the right way to solve their needs? 

Issues:
- [ ] #1165 
- [ ] #1166

**Comment by rackstar** [comment]
![dashboard-data drawio (1)](https://github.com/NexusMutual/smart-contracts/assets/15180121/f90ff2be-2441-4185-865d-6fb86ac95818)

https://nexusmutual.slack.com/archives/C04JG2C41J4/p1718790233399679

**Comment by rackstar** [comment]
## Get managed staking pools by manager address

### Current (1 contract call + filtering)
1. fetching all staking pools (StakingViewer.getStakingPoolsOf)
2. filtering by ‘manager’ address

### Proposed improvement (1 contract call)
new StakingViewer method `getManagedStakingPools` that takes in manager address
```javascript
stakingViewer.getManagedStakingPools(managerAddress) => Pool[]
```

## Get manager rewards for user (address)

### Current (2 contract calls)
1. fetching all staking pools to get the pool Ids of tokenIds - `stakingViewer.getStakingPoolsOf(tokenIds)`
2. call `stakingViewer.getManagerRewards(poolId)`

### Propose improvement (1 contract call)
new StakingViewer method `getManagerTokenRewards` that takes in manager address
```javascript
stakingViewer.getManagerTokenRewards(managerAddress) => Token[]
```

**Comment by rackstar** [comment]
## Process Expiration

### Current (2 contract calls)
1. fetch the poolIds of tokenIds - `stakingViewer.getStakingPoolsOf(tokenIds)`
2. call processExpirations with poolIds - `stakingViewer.processExpirations(poolIds)`
currently address => tokenId => poolId

TODO: stakingViewer.processExpirationsFor(tokenIds)

* alchemy.getNftsForOwner(address) => tokenIds[]
* getStakingPoolsOf(tokenIds) => { poolId, tokenId }
  * stakingViewer.processExpiration()

**Comment by rackstar** [comment]
## INexusViewer

```solidity
interface INexusViewer {
    struct AssessmentRewards {
        uint totalPendingAmountInNXM;
        uint withdrawableAmountInNXM;
        uint withdrawableUntilIndex;
    }

    struct ClaimableNxm {
        AggregatedTokens aggregatedTokens;
        uint govPendingRewards;
        Staker legacyPoolStake;
        AssessmentRewards assessmentRewards;
    }

    struct StakedNxm {
        AggregatedTokens aggregatedTokens;
        Stake assessmentStake;
    }

    struct PoolsAndRewards {
        Pool[] pools;
        Token[] rewards;
    }

    struct WithdrawableCoverNotes {
        uint[] coverIds;
        bytes32[] lockReasons;
        uint withdrawableAmount;
    }

    /* ========== VIEWS ========== */

    function stakingViewer() external view returns (address);

    function getClaimableNxm(address user, uint[] calldata tokenIds) external view returns (ClaimableNxm memory);

    function getStakedNxm(address manager, uint[] calldata tokenIds) external view returns (StakedNxm memory);

    function getManagedPoolsAndRewards(address manager) external view returns (PoolsAndRewards memory);

    /* ========== DEPENDENCIES ========== */

    function legacyPooledStaking() external view returns (address);

    function assessment() external view returns (address);

    function governance() external view returns (address);

    function tokenController() external view returns (address);

    function changeDependentContractAddress() external;
}
```

**Comment by roxdanila** [comment]
Regarding Get claimable NXM:
One thing that's missing there is the claim assessment voting stake that might be unlocked ( Assessment.stakeOf account) - needs additional logic to decide if it's locked or not - check Assessment.unstake() function. Maybe we need a function in the contract that returns true/false if the stake is locked.

**Comment by roxdanila** [comment]
Regarding Get Staked NXM:
- we should make sure we only count staking deposits and claim assessment stakes that are currently locked

**Comment by roxdanila** [comment]
Regarding Get managed pool and rewards: 

Alternative naming:

```
struct ManagerPoolsAndRewards { // new struct
    Pool[] pools; // struct from IStakingViewer
    Token[] rewards; // struct from IStakingViewer
}

function getManagerPoolsAndRewards(address manager) external view returns (ManagerPoolsAndRewards);
```

**Comment by rackstar** [comment]
Continued discussion here:
https://docs.google.com/document/d/1MLjGrUcfnUwRsONhXJD-IENw-TEMmdKVM9ayut1ApsQ/edit

**Comment by roxdanila** [comment]
Closing in favour of the 2 issues mentioned in the description
