### ISSUE TITLE
[NMPIP] Investment: Allocate 14,400 ETH to Rocket Pool Protocol rETH

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#896]
Step 0: No-action proposal voted by all members to allow the AB to implement the investment.
  - All members vote
  - Onchain vote start date: July 12th, 2023
  - Proposal title & description: https://docs.google.com/document/d/1obHOZj7CyCHtGzVoYDUxlUUWBamLKFZym9ljPT-yPOY/edit

Step 1: Add new price feed oracle
- **Price Feed Oracle**: rETH / ETH Chainlink oracle: https://data.chain.link/ethereum/mainnet/crypto-eth/reth-eth
- Deploy the new PriceFeedOracle.sol contract to use the above oracle
- Governance proposal to use the new PriceFeedOracle.sol address internally
  - AB only
  - Onchain vote start date: Monday, July 17th 2023
  
Step 2: Edit Add new Asset category
The current signature of addAsset is addAsset(address,bool,uint256,uint256,uint256) and does not match the signature of proposal category 42.
  - AB only
  - Onchain vote start date: Monday, July 17th 2023
  
Step 3: Add new asset
- **Asset Address**: rETH (https://etherscan.io/token/0xae78736cd615f374d3085123a210448e74fc6393)
- **Can cover be bought in this asset**: No (`isCoverAsset = false`)
- **Min / max values**
    - We can trade only below min and above max - [min, max] interval is a no trade zone
    - **Min value**: 13362
    - **Max value**: 13400
- **Max slippage ratio**: 0.2%
- Governance proposal to add the new asset with the above details
    - AB only
    - Onchain vote start date: Monday, July 17th 2023
 

Step 4: Tx to open limit order on Cowswap to sell 14400ETH for rETH.

**Comment by danoctavian** [comment]
Category
42. Add Asset to Pool

Can vote: Advisory Board
Can propose: Advisory Board

40. Update Pool address parameters (PRC_FEED)

Can vote: Advisory Board
Can propose: Advisory Board

**Comment by hughkarp** [comment]
Can we drop the max slippage ratio, eg to 0.20% or something. 1% is 3 months yield.

**Comment by rmelbardis** [comment]
Let's change **Min value** to 13362 as per slack discussion, and agree with Hugh on slippage.
