### ISSUE TITLE
Tokenomics - RAMM

### ISSUE THREAD

**Issue by Ethwookie** [NexusMutual/smart-contracts#917]
Hello, given that RAMM transactions will have price impact, I think it would be beneficial to have slippage settings like Uniswap (minAmountOut).

**Comment by roxdanila** [comment]
It does, you can check it here: https://github.com/NexusMutual/smart-contracts/pull/926/files#diff-0938769b9e885f082aa1c7b60f9e8b77439a199286c8946dc1e5c30c7a4124caR106-R110

**Comment by Ethwookie** [comment]
Posted this months ago when it didn’t :)
