### ISSUE TITLE
Remove solmate and @openzepplin/contracts v2.5.1 dependencies

### ISSUE THREAD

**Issue by shark0der** [NexusMutual/smart-contracts#929]
We currently have `@openzeppelin/contracts@^2.5.1` and `solmate` dependencies in the contracts repo. 

- Solmate is only used in a mock contract
- OZ 2.5.1 is used in various mocks, as well as in `LegacyClaimsData`, `LegacyQuotationData` and `Governance`

We need to:

- [ ] Copy OZ v2.5.1's `SafeMath.sol` to `contracts/contracts/modules/governance/external/`
- [ ] Update `LegacyClaimsData`, `LegacyQuotationData` and `Governance` to use the copied over `SafeMath` library
- [ ] Reimplement the mock ERC721 contract (can be based on solmate similar to how we implemented `CoverNFT` and `StakingNFT` contracts)
- [ ] Make sure there aren't any contracts still using the deps that are about to be removed
- [ ] Remove oz 2.5.1 and solmate deps
- [ ] Remove the custom npm name of oz v4 dep and update all imports accordingly
- [ ] Make sure all tests are still passing

**Comment by JensonCollins** [comment]
@shark0der I would like to contribute this project by resolving this issue. How can I get started?
