### ISSUE TITLE
Tokenomics: RAMM Integrations Tests

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#938]

**Comment by roxdanila** [comment]
TODO @roxdanila & @shark0der - come up with more cases to test

**Comment by roxdanila** [comment]
TODO - sort out the dynamic token price in integration tests

**Comment by roxdanila** [comment]
- token price calculation setup + fix recently skipped ones
- token price after cover buy
- token price after claim

TODOs re fixing mocks in contracts/mocks/Claims/CLMockPool.sol and contracts/mocks/Cover/CoverMockPool.sol

**Comment by rackstar** [comment]
* [x] token price calculation setup + fix recently skipped ones - https://github.com/NexusMutual/smart-contracts/pull/982/
* [x] token price after cover buy - https://github.com/NexusMutual/smart-contracts/pull/982/
* [x] fixing mocks in contracts/mocks/Claims/CLMockPool.sol and contracts/mocks/Cover/CoverMockPool.sol - https://github.com/NexusMutual/smart-contracts/pull/976
* [ ] token price after claim
