### ISSUE TITLE
Tokenomics: Ramm-only emergency pause mechanics

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#961]
@shark0der to provide more details

**Comment by rackstar** [comment]
* system wide pause mechanism - boolean flag pause
* Ramm specific pause mechanism for just the swap
* logic reside in Ramm
* just a flag
* multisig emergency pause address - allow only that address to pause / un-pause Ramm contract
* swap should also listen to global pause (should be in IMasterAware)
* whenSwapNotPause
* modifier - swap on or off
* define new modifier that reads both global and local Ramm values

**Comment by rackstar** [comment]
### whenSwapNotPaused

modifier should only allow calls if BOTH system and swap is NOT on emergency pause

* both system and Ramm paused - **PREVENT** call with "System is paused"
* system is paused / Ramm is NOT paused - **PREVENT** call with "System is paused"
* system is NOT paused / Ramm paused - **PREVENT** call with "Ramm is paused"
* both system and Ramm are NOT paused - **ALLOW**


### whenSwapPaused

modifier should only allow calls if either system or swap is on emergency pause

* both system and Ramm paused - **ALLOW**
* system is paused / Ramm NOT paused - **ALLOW**
* system is NOT paused / Ramm is paused - **ALLOW**
* both system and Ramm are NOT pause - **PREVENT** with "Swap is NOT paused"
